feat(arrs): add support for including unmonitored titles
autobrr/omegabrr pull request #96
Opened 2024-11-04 10:41 UTC by s0up4200

Closes #95

2024-11-04 11:18 UTC, frant4 approved these changes

2024-11-05 17:27 UTC, zze0s requested changes
LGTM! Just some minor changes needed for the import order to keep it consistent.

2024-11-05 17:27 UTC, zze0s commented on internal/domain/config.go
> +	"github.com/autobrr/omegabrr/internal/apitoken"
Minor thing but we usually order imports like: stdlib, application, 3rd party

2024-11-05 17:27 UTC, zze0s commented on internal/processor/radarr.go
> +	"github.com/autobrr/omegabrr/pkg/autobrr"
Import order

2024-11-05 17:27 UTC, zze0s commented on internal/processor/service.go
> +	"github.com/autobrr/omegabrr/pkg/autobrr"
Import order.

2024-11-05 17:27 UTC, zze0s commented on internal/processor/sonarr.go
> +	"github.com/autobrr/omegabrr/pkg/autobrr"
Import order.

2024-11-06 11:41 UTC, zze0s approved these changes

2024-11-06 11:41 UTC, merged